### ISSUE TITLE
Problem while compiling it

### ISSUE THREAD

**Issue by jganzabal** [garydoranjr/pyemd#1]
Hi there, I was trying to install it, and I got:
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/julianganzabal/anaconda/include -arch x86_64 -Ic_emd -I/Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include -I/Users/julianganzabal/anaconda/include/python3.5m -c c_emd/pyemd.c -o build/temp.macosx-10.6-x86_64-3.5/c_emd/pyemd.o
    In file included from c_emd/pyemd.c:5:
    In file included from /Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1788:
    /Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    c_emd/pyemd.c:82:5: warning: implicit declaration of function 'Py_InitModule3' is invalid in C99 [-Wimplicit-function-declaration]
        Py_InitModule3("c_emd", c_emd_methods,
        ^
    c_emd/pyemd.c:84:5: error: void function 'initc_emd' should not return a value [-Wreturn-type]
        import_array();
        ^~~~~~~~~~~~~~
    /Users/julianganzabal/anaconda/lib/python3.5/site-packages/numpy/core/include/numpy/__multiarray_api.h:1532:144: note: expanded from macro 'import_array'
    #define import_array() {if (_import_array() < 0) {PyErr_Print(); PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                                                                                   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~
    2 warnings and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Users/julianganzabal/anaconda/bin/python -c "import setuptools, tokenize;__file__='/usr/local/Cellar/opencv3/3.2.0/lib/python2.7/src/pyemd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /usr/local/Cellar/opencv3/3.2.0/lib/python2.7/src/pyemd/

I have no clue how to solve it!  ;)
I am using MAC OS with sierra
Thank it advance
Julian

**Comment by jganzabal** [comment]
OK, It had to do with python version, so I run it on a python 2.7 enviroment and it worked!

**Comment by garydoranjr** [comment]
Hi Julian, glad that you got it to work!
