### ISSUE TITLE
Import Error undefined symbol Py_InitModule3

### ISSUE THREAD

**Issue by shanealynn** [garydoranjr/pyemd#2]
Great module, or looks great anyway. Looking to use with Python 3.6.0 anaconda build, but no look through github clone install or pip install through github - can't import with error as in title. :(

**Comment by garydoranjr** [comment]
Unfortunately, this module doesn't currently support Python 3, so that's likely the cause of the error you're seeing.

**Comment by shanealynn** [comment]
Well. This makes perfect sense. Thanks. And apologies for the rather redundant question!
