### ISSUE TITLE
how to define the ground distance?

### ISSUE THREAD

**Issue by muzi-8** [garydoranjr/pyemd#4]
If the Param 'distance = precomputed',how to define the ground distance.
for example:
X = np.array([100.0,0.0,0.0,0.0,120.0,0.0])
Y =np.array([0.0,100.0,0.0,0.0,0.0,120.0])
how we should to manually define the ground distance?
and the distance size is (1,1)?
Thanks!

**Comment by garydoranjr** [comment]
Hello @muzi-8,

The X and Y arguments are intended to define the points along the ground (in the case of a one-dimensional example). However, for 1-D, X and Y should be a single column (the columns of X and Y contain each dimension for multi-dimensional cases).

If you've already computed histograms (as perhaps these are), then these arguments should be used as X_weights and Y_weights arguments. You should normalize these histograms to sum to 1. In this case, if you define X and Y to be the centers of the histogram bins, then you can use a standard (e.g., Euclidean) distance. Or you can omit the arguments X and Y and provide a custom pre-computed distance matrix (X and Y are ignored when a precomputed distance matrix is provided).

If you use a precomputed matrix with a 1-D weight array with 6 elements, then the distance matrix should be 6x6 in size.
