### ISSUE TITLE
cDist function

### ISSUE THREAD

**Issue by wasih123** [garydoranjr/pyemd#6]
Hey
I was looking through the code, but was unable to find the cDist function called in pyemd.py file.
Can you please tell where I would find it? It is not there in emd folder also.

**Comment by garydoranjr** [comment]
Hi @wasih123 the cdist function is imported from `scipy` here: https://github.com/garydoranjr/pyemd/blob/57fb492e72813bd3d4d841a8b61d89c76ba137bf/emd/emd.py#L5
